spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

  application:
    name: productmgmt

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/productDB;AUTO_SERVER=TRUE
    username: sa
    password:

